### ISSUE TITLE
Starcounter.TransactionLog not available

### ISSUE THREAD

**Issue by jwillmer** [per-samuelsson/SweOffshoreReplicator#1]
I installed the latest Starcounter from the nightly builds but I am still missing this namespace to compile the project.

**Comment by per-samuelsson** [comment]
> I installed the latest Starcounter from the nightly builds but I am still missing this namespace to compile the project.

Sorry, didn't see this until now. You'll have to use the "PNext" nightly builds. We are about to make the switch over to make that version or current HEAD. Let me know if you want me to assist you with that!
